services:
  app:
    image: node:22.8.0-bullseye
    container_name: app
    restart: unless-stopped
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app